---
# handlers file for roles/hw9.role

- name: nginx-start
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: nginx-reload
  systemd:
    name: nginx
    state: reloaded

- name: nginx-test
  uri:
    url: http://localhost:{{ nginx_listen_port }}
    return_content: no