# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :lesson13ipaserver => {
        :box_os => "centos/7",
        :ip_addr => '192.168.10.101',
        #:fw_ports => 1
  },
  :lesson13client => {
        :box_os => "centos/7",
        :ip_addr => '192.168.10.102',
        #:fw_ports => 0
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_os]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          #if :fw_ports == 1
              #box.vm.network "forwarded_port", guest: 80, host: 80
              #box.vm.network "forwarded_port", guest: 443, host: 443
          #end
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "3072"]
            vb.customize ["modifyvm", :id, "--cpus", "6"]
          end
          box.vm.provision "shell", path: "provi.sh"
      end
  end
end

