# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :lesson14elk => {
        :box_os => "centos/7",
        :ip_addr => '192.168.10.143',
        :provision_sh => "p_elk.sh",
  },
  :lesson14log => {
        :box_os => "centos/7",
        :ip_addr => '192.168.10.142',
        :provision_sh => "p_log.sh",
  },
  :lesson14web => {
        :box_os => "centos/7",
        :ip_addr => '192.168.10.141',
        :provision_sh => "p_web.sh",
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_os]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "4096"]
            vb.customize ["modifyvm", :id, "--cpus", "6"]
          end
          box.vm.provision "shell", path: boxconfig[:provision_sh]
      end
  end
end