home = ENV['HOME']
vm_name = 'test2'
vm_disks_place = home + '/VB_VMs/' + vm_name + '/'

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.10.102"
    config.vm.host_name = vm_name.to_s
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"]
        vb.customize ["modifyvm", :id, "--cpus", "6"]
        vb.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
        (2..5).each do |n|
             vm_disk = vm_disks_place + "vm_disk#{n}.vdi"
             unless File.exist?(vm_disk)
                    vb.customize ["createhd", "--filename", vm_disk, "--size", "1024"]
             end
             vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", "#{n}", "--type", "hdd", "--medium", vm_disk]
        end
    end
    config.vm.provision "shell", path: "create_array.sh"
    config.vm.provision "shell", path: "create_partitions.sh"
    config.vm.provision "shell", path: "fail_repair_raid.sh"
end
