home = ENV['HOME']
vm_name = 'lesson-08'
vm_disks_place = home + '/VB_VMs/' + vm_name + '/'

Vagrant.configure(2) do |config|
    config.vm.box = "cdaf/CentOSLVM"
    config.vm.network "private_network", ip: "192.168.10.103"
    config.vm.host_name = vm_name.to_s
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cpus", "6"]
    end
end
