home = ENV['HOME']

MACHINES = {
    :repodocker => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
        }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "4096"]
                vb.customize ["modifyvm", :id, "--cpus", 6]
            end
            box.vm.provision "shell", path: "startup.sh"
            box.vm.provision "shell", path: "rpmbuild.sh"
            box.vm.provision "shell", path: "installdocker.sh"
            box.vm.provision "shell", path: "rundocker.sh"
        end
    end
end
