---
# tasks file for roles/hw9.role

- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present
  notify:
    - nginx-start

- name: recreate nginx.conf from template
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - nginx-reload
    - nginx-test

